app_perris/urls.py
from django.conf.urls import include , url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('contactanos', views.contacto, name='contacto'),
    path('lista-usuarios', views.listar, name ='lista'),
    path('lista-mascota', views.masclist, name='masclist'),
    path('mascota', views.crea_mascotas, name='crea_mascotas'),
    path('update/<int:id>/',views.upd_mascota , name="upd_mascota"),
    path('delete/<int:id>/', views.del_mascota, name="del_mascota"),
     
    path('Mascota/rescatados', views.listar_resc, name='rescatado'),
    path('Mascota/adoptados', views.listar_adop, name='adoptados'),
    path('Mascota/disponibles', views.listar_disp, name='disponibles'),
    path('Servicios', views.servicio, name="servicios")

    
]

cuentauser/urls.py
from django.conf.urls import url
from . import views


app_name = 'accounts'

urlpatterns=[
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^recuperar/$', views.recuperar_view, name="recuperar"),
]

misperris_arroyo/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from . import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app_perris.urls')),
    url(r'^cuentauser/', include('cuentauser.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_perris/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    correo = models.CharField(max_length=40)
    rut = models.CharField(max_length=11)
    nombre = models.CharField(max_length=40)
    fechaNacimiento = models.DateField()
    telefono = models.IntegerField()
    region =  models.CharField(max_length=40)
    ciudad =  models.CharField(max_length=40)
    tipoCasa =  models.CharField(max_length=40)

    def guardar(self):
        self.save()
    
    def __str__(self):
        return self.nombre


class Mascota(models.Model):
    fotografia = models.ImageField(upload_to='fotos/')
    nombre = models.CharField(max_length=40)
    razaPredominante = models.CharField(max_length=40)
    descripcion = models.TextField()
    estado = models.CharField(max_length=20)


    def guardar(self):
        self.save()
    
    def __str__(self):
        return self.nombre

cuentauser/models.py
from django.db import models

# Create your models here.

app_perris/forms.py
from django import forms

from .models import Usuario, Mascota

class RegFormulario(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = (
                  'correo', 
                  'rut', 
                  'nombre', 
                  'fechaNacimiento', 
                  'telefono', 
                  'region', 
                  'ciudad', 
                  'tipoCasa'
                  )


class MascotaFormulario(forms.ModelForm):
    fotografia = forms.ImageField()
    class Meta:
        model = Mascota
        fields = (
            'fotografia',
            'nombre',
            'razaPredominante',
            'descripcion',
            'estado',
        )

app_perris/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect, redirect
from django.template import RequestContext
from .models import Usuario, Mascota
from .forms import RegFormulario, MascotaFormulario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

# Create your views here.

def inicio(request):
    return render(request, 'perris/index.html')


@login_required(login_url="/accounts/login/")
def contacto(request):

    if request.method == 'POST':
        form = RegFormulario(request.POST)
        if form.is_valid():
            form.save()
          
            return  redirect('servicios')
    else:
        form = RegFormulario()
        return render(request, 'perris/formulario.html', {'form': form})
        

@login_required(login_url="/accounts/login/")
def servicio(request):
    return render(request, 'perris/servicio.html')


@login_required(login_url="/accounts/login/")
def listar(request):
    Usuarios = Usuario.objects.all().orderby('nombre')
    return render(request, 'perris/listausuarios.html', {'lista': Usuarios})


@login_required(login_url="/cuentauser/login/")
def crea_mascotas(request):
    if request.method == "POST":
        form = MascotaFormulario(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            form.save()
            mascotas = Mascota.objects.all()
            return render(request, 'perris/mascotalista.html', {'listam': mascotas})
    else:
        form = MascotaFormulario()
        return render(request, 'perris/formulariomascota.html', {'form': form})


@login_required(login_url="/accounts/login/")
def masclist(request):
    mascotas = Mascota.objects.all()
    return render(request, 'perris/mascotalista.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def upd_mascota(request, id):
    mascota = Mascota.objects.get(id=id)
    form = MascotaFormulario(request.POST or None, instance=mascota)
    print(mascota.nombre)
    if form.is_valid():
        form.save()
        mascotas = Mascota.objects.all()
        return render(request, 'perris/mascotalista.html', {'listam': mascotas})
    
    return render(request, 'perris/formulariomascota.html', {'mascota': mascota}) 

@login_required(login_url="/accounts/login/")
def del_mascota(request, id):
    mascota = Mascota.objects.get(id=id)

    if request.method == 'POST':
        mascota.delete()
        mascotas = Mascota.objects.all()
        return render(request, 'perris/mascotalista.html', {'listam': mascotas})

    return render(request, 'perris/confirmacion.html', {'mascota': mascota})

@login_required(login_url="/accounts/login/")
def listar_resc(request):
    mascotas = Mascota.objects.all().filter(estado='Rescatado')
    return render(request, 'perris/mascotasrescatados.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def listar_adop(request):
    mascotas = Mascota.objects.all().filter(estado='Adoptado')
    return render(request, 'perris/mascotaadoptados.html', {'listam': mascotas})

@login_required(login_url="/accounts/login/")
def listar_disp(request):
    mascotas = Mascota.objects.all().filter(estado='Disponible')
    return render(request, 'perris/mascotadisponibles.html', {'listam': mascotas})

cuentauser/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()#loggea al user
            login(request, user)
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('inicio')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('inicio')


def recuperar_view(request):
    if request.method == 'POST':
        return redirect('accounts:login')
    return render(request, 'accounts/recuperar.html')

app_perris/templates/perris/confirmacion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Confirmacion de eliminación</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <h2>¿Estas seguro que quieres remover la mascota {{ mascota.nombre }}?</h2>
        <button type="submit">Confirmar</button>
    </form>
</body>
</html>

app_perris/templates/perris/formulario.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <title>formulario</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo-formulario.css' %}" />
</head>
<body>
    <div class="anch">
        <div class="box1">
                <img id="logo" src="{% static 'img/logo.png' %}" alt="">
        </div>
    
        <div class="box2">
                <nav class="menu">
                        <ul>
                                <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                                {% if not user.is_active %}
                                <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                {% endif %}
                                <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>
                                {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                {% endif %}
                            </ul>
                </nav>
        </div>
    </div>

    <br/>
    <div class= "label";>
        <label>FORMULARIO DE ADOPCIÓN</label>    
    </div>
    
    <div class="borde">
       
       <form method="POST" > {% csrf_token %}
        <br/>
        <div class="left"> Correo electrónico: </div> <div class="right"><input type="text" name="correo" placeholder="micorreo@gmail.com" required/></div> <br />
        <br />
        <br />
        
        <div class="left"> Run: </div> <div class="right"><input type="text" id="rut" name="rut" required oninput="checkRut(this)" placeholder="Ingrese RUN">
             <script src="{% static 'js/rut.js' %}"></script></div> <br />
        <br />
        <br />
        
        <div class="left"> Nombre Completo: </div> <div class="right"><input type="text" name="nombre" required minlength="1"/></div> <br />
        <br />
        <br />
        
        <div class="left"> Fecha de Nacimiento: </div> <div class="right"><input type="date" name="fechaNacimiento" required max="2000-12-31"/></div> <br />
        <br />
        <br />
        
        <div class="left"> Teléfono de Contácto: +56 </div> <div class="right"><input type="number" name="telefono" max="999999999"/></div> <br />
        <br />
        <br />
        
        <div class="left"> Región: </div> <div class="right"><select id="region" name="region" required>
            <option>XV Arica y Parinacota</option>
            <option>I Tarapacá</option>
            <option>II Antofagasta</option>
            <option>III Atacama</option>
            <option>IV Coquimbo</option>
            <option>V Valparaíso</option>
            <option>VI O'Higgins</option>
            <option>Región Metropolitana</option>
            <option>VII Maule</option>
            <option>VIII Biobío</option>
            <option>IX La Araucanía</option>
            <option>XIV Los Ríos</option>
            <option>X Los Lagos</option>
            <option>XI Aysén</option>
            <option>XII Magallanes y Antártica</option>
            </select></div> <br />
    <br />
    <div class="left"> Ciudad: </div> <div class="right"><select id="ciudad" name="ciudad" required>
            <option>concepción</option>
            <option>santiago</option>
            <option>chillan</option>
            <option>valdivia</option>
            <option>talca</option>
            <option>valparaiso</option>
            <option>osorno</option>
            <option>talcahuano</option>
            </select></div> <br />
    <br />
    <div class="left"> Tipo de vivienda: </div> <div class="right"><select id="vivienda" name="tipoCasa" required>
                        <option>Casa con patio grande</option>
                        <option>Casa con patio pequeño</option>
                        <option>Casa sin patio</option>
                        <option>Departamento</option>
                      </select></div><br/>
    <br/>
    <div class="left"> <button type="submit">Registrar</button></div>     
    <br/>
        
    </form>
   </div>

</body>
</html>

app_perris/templates/perris/formulariomascota.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/mantenedor.css' %}" />
    <title>Formulario para registrar mascota</title>
</head>
<body>
    <div class="container1">
        <div class="anch">
            <div class="box1">
                    <img id="logo" src="{% static 'images/logo.png' %}" alt="">
            </div>
        
            <div class="box2">
                    <nav class="menu">
                            <ul>
                                    <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>
                                    {% if user.is_active %}
                                        <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                        <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                    </nav>
            </div>
        </div>
        
        <div>
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                <br>
                <br>
                <div class="left"> Subir fotografia: </div> <div class="left"><input type="File" name="fotografia" accept="image/png, .jpeg, .jpg, image/gif"></div> 
                <br>
                <br>
                <div class="left"> Nombre: </div> <div class="right"><input type="text" name="nombre" required minlength="1" maxlength="40" value="{{ mascota.nombre }}"></div> 
                <br>
                
                <div class="left"> Raza: </div> <div class="right"><input type="text" name="razaPredominante" required minlength="1" maxlength="40" value="{{ mascota.razaPredominante }}"></div>
                <br>
                
                <div class="left"> Descripción: </div> <div class="right"><input type="text" name="descripcion" required minlength="1" maxlength="100" value="{{ mascota.descripcion }}"></div>
                <br>
               
                <div class="left"> Estado: </div> <div class="right"><select id="estado" name="estado" required>
                        <option>Rescatado</option>
                        <option>Disponible</option>
                        <option>Adoptado</option>
                      </select></div><br/>
                <br/>
                <div class="left"> <button type="submit">Guardar</button></div>     
                <br/>
                {% if mascota %}
                    <a href="{% url 'del_mascota' mascota.id %}">Delete</a>
                {% endif %}

            </form>

            
        </div>
</body>
</html>

app_perris/templates/perris/index.html
<!DOCTYPE html>
{% load static %}
<!--integrantes: Juan Arroyo Vergara, Christopher Rivas Roa-->
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/banner.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/container2.css' %}">
    <script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
    
    <title>Mis Perris</title>
</head>
<body>
  <main>  
    <header>
    <!--<h1>encabezado</h1>-->
     <div class="contenedor">
         <img src="{% static 'images/logo.png' %}" alt="">
         <input type="checkbox" id="menu-bar">
         <label class="icon-menu" for="menu-bar"></label> 
         <nav class="menu">
            <!--<h1>menu</h1>-->
            <ul>
                    <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                    {% if not user.is_active %}
                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                    {% endif %}
                    <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>
                    {% if user.is_active %}
                        <li class="l"><a href="">{{user.username}}</a></li>
                    {% else %}
                        <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                    {% endif %}
                </ul>
            </nav>
         </div>
    </header>
    
  
    <section id="banner">
       <h2>seccion slider y sociales</h2>
           <div class="slider">
             <ul>
                 
                 <li><img src="{% static 'images/Tom.jpg' %}" alt="">
                <div class="contenedor">
                     <p id="parrafo">"Estamos felices de tener a nuestro nuevo compañero en casa."</p>
                 </div>
                 </li>
                 <li><img src="{% static 'images/Duque.jpg' %}" alt=""></li>
                 <li><img src="{% static 'images/Apolo.jpg' %}" alt=""></li>
                
              </ul>        
              <div class="sociales">
                      <a class="icon-facebook" href="#"></a>
                      <a class="icon-google" href="#"></a>
                      <a class="icon-instagram" href="#"></a>
                      <a class="icon-mail" href="#"></a>
                  </div>
                  
             
              </div>
              
    </section>
    
    
    <section id="rescate">
          <h2>seccion rescate y financiamiento</h2>
          <div class="container2">
                <div class="articulo1">
                        <h4>RESCATE</h4>
                        <H6>ETAPA UNO</H6>
                        <h6>_______</H6>
                        <br>
                        <p>Rescatamos perritos en situación de peligro y/o abandono. Los rehabilitamos y los</p>
                        <p>preparamos para buscarles un hogar.</p>
                        <br>
                        <img src="{% static 'images/rescate.jpg' %}" alt="">
                </div>
                <div class="articulo2">
                        <img src="{% static 'images/crowfunding.jpg' %}" alt="">
                        <h4>CROWDFUNDING</h4>
                        <h6>FINANCIAMIENTO</h6>
                        <h6>_______</h6>
                        <br>
                        <p>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y</p>
                        <p>actividades que realizamos para obtener financiamiento para seguir ayudando</p>
                        <br>
                        <input type="button" value="CAMPAÑAS">
                </div>
            </div>
    </section>
    
 
    
   <div class="gallery">
        <a href="{% static 'images/Bigotes.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Bigotes, soy un perrito muy jugueton y regalon.">
        <img src="{% static 'images/Bigotes_tn.jpg' %}" alt=""></a>
        <a href="{% static 'images/Luna.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Luna, soy una perrita muy juggetona">
        <img src="{% static 'images/Luna_tn.jpg' %}" alt=""></a>
        <a href="{% static 'images/Maya.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Maya, soy una perrita pequeña muy regalona">
        <img src="{% static 'images/Maya_tn.jpg' %}" alt=""></a>
        <a href="{% static 'images/Oso.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Oso, soy un perrito que le gusta mucho jugar al aire libre">
        <img src="{% static 'images/Oso_tn.jpg' %}" alt=""></a>
        <a href="{% static 'images/Pexel.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Pexel, soy un perrito muy pequeño al que le gusta jugar mucho">
        <img src="{% static 'images/Pexel_tn.jpg' %}" alt=""></a>
        <a href="{% static 'images/Wifi.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Wifi, soy un perrito con un diseño de manchas muy tierno">
        <img src="{% static 'images/Wifi_tn.jpg' %}" alt=""></a>
         <a href="{% static 'images/Chocolate.jpg' %}" data-lightbox="mygallery" data-title="Mi nombre es Chocolate, soy un perro grande que le gusta pasear y jugar">
        <img src="{% static 'images/Chocolate_tn.jpg' %}" alt=""></a>
   </div>

  </main>
 <footer>
 	 <div class="pie">
              
      <h5>Desarrollo Web y Mobile</h5>
              
           </div>
 </footer>
 
  
  
</body>
</html>

app_perris/templates/perris/listausuarios.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo.css' %}" />
    <title>Document</title>
</head>
<body>
        <div class="anch">
                <div class="box1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="box2">
                        <nav class="menu">
                                        <ul>
                                                        <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                                                        {% if not user.is_active %}
                                                        <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                                        {% endif %}
                                                        <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>
                                                        {% if user.is_active %}
                                                            <li class="l"><a href="">{{user.username}}</a></li>
                                                        {% else %}
                                                            <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                                        {% endif %}
                                                    </ul>
                        </nav>
                </div>
            </div>
            
    <h1 text-align="center">Lista Usuario</h1>
    <br>
    {% for alguien in lista %}
    <div>
        <p text-align="center">{{alguien.nombre}}</p>
        <br>
    </div>
    {% endfor %}

    <a href="{% url 'contacto' %}">Volver</a>
</body>
</html>

app_perris/templates/perris/mascotalista.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo-mascota.css' %}" />
    <title>Lista de Mascotas</title>
</head>
<body>
        <div class="anch">
                <div class="contenedor1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="contenedor2">
                        <nav class="menu">
                                <ul>
                                        <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                                        {% if not user.is_active %}
                                        <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                        {% endif %}
                                        <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>
                                        {% if user.is_active %}
                                        <li class="l"><a href="">{{user.username}}</a></li>
                                        {% else %}
                                        <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                        {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
            <div id="crud">
                {% if request.user.is_superuser %}
                        <a href="{% url 'crea_mascotas' %}">Agregar nuevo</a>
                        <a href="{% url 'rescatado' %}">Ver rescatados</a>
                        <a href="{% url 'adoptados' %}">Ver adoptados</a>
                        <a href="{% url 'disponibles' %}">Ver disponibles</a>
                {% else %}
                        <a href="{% url 'disponibles' %}">Ver disponibles</a>
                        <br>
                        <br>
                {% endif %}
                        </div>
            <div class="borde">
               
        <h1>Lista Mascotas</h1>
        {% for mascota in listam %}
        <div>
                <a href="{% url 'upd_mascota' mascota.id %}">
                        <img src="{{ mascota.fotografia.url }}" alt="">
                        <br> 
                        {{mascota.nombre}}
                </a>   
                
                <br>
        </div>
        {% endfor %}

        
    </div>

    <div class="pie">
                <footer>
                 {% if user.is_active %}
                     <form method="POST" action="{% url 'accounts:logout' %}">
                         {% csrf_token %}
                         <h5>Conectado Como {{user.username}}</h5>
                         <br>
                         <button type="submit" >Cerrar Sesión</button>
                         
                     </form>
                 {% endif %}
                </footer>
     </div>

   
</body>
</html>

app_perris/templates/perris/servicio.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/estilo-mascota.css' %}" />
    <title>Servicios</title>
</head>
<body>
        <div class="anch">
                <div class="contenedor1">
                        <img id="logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
            
                <div class="contenedor2">
                        <nav class="menu">
                                <ul>
                                    <li class="l"><a href="{% url 'inicio' %}">Inicio</a></li>
                                    {% if not user.is_active %}
                                    <li class="l"><a href="{% url 'accounts:signup' %}">Registrarse</a></li>
                                    {% endif %}
                                    <li class="l"><a href="{% url 'servicios' %}">Servicios</a></li>  
                                    {% if user.is_active %}
                                    <li class="l"><a href="">{{user.username}}</a></li>
                                    {% else %}
                                    <li class="l"><a href="{% url 'accounts:login' %}">Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                        </nav>
                </div>
            </div>
    <div class="borde">
        <h1>Servicios</h1>
        {% for mascota in listam %}
        <div>
                <a href="{% url 'update_mascota' mascota.id %}">
                        <img src="{{ mascota.fotografia.url }}" alt="">
                        <br> 
                        <h4>Nombre: {{mascota.nombre}}</h4>
                        <h4>Raza predominante: {{mascota.razaPredominante}}</h4>
                        <h4> Descripcion: {{mascota.descripcion}}</h4>
                        <h4>Estado: {{mascota.estado}}</h4>
                </a>   
                
                <br>
        </div>
        {% endfor %}

        {% if request.user.is_superuser %}
                <br>
                <a href="{% url 'masclist' %}"><h1>Gestion de Mascotas de la asociación</h1></a>
                <br>
                <br>
                
        {% else %}
                <br>
                <br>
                <a href="{% url 'disponibles' %}"><h1>Adoptar Mascotas Disponibles</h1></a>
                <br>  
                <br>
        {% endif %}
       
    </div>
    <div class="pie">
            <footer>
             {% if user.is_active %}
                 <form method="POST" action="{% url 'accounts:logout' %}">
                     {% csrf_token %}
                     <h5>Usuario {{user.username}}</h5>
                     <br>
                     <button type="submit" >Cerrar Sesión</button>
                     
                     
                 </form>
             {% endif %}
            </footer>
    </div>
    

   
</body>
</html>